apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: v3

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 6.14.8
    condition: mysql