image:
  repository: krasfree/otus

config:
  host: mysql
  db: otus-test

service:
  type: NodePort
  port: 8000
  targetPort: 80

replicaCount: 2

ingress:
  host: "arch.homework"
  path: "/otusapp/dmansurov($|/)(.*)"

mysql:
  fullnameOverride: mysql
  root:
    password: "123456"
  replication:
    enabled: false
  master:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  service:
    type: NodePort
    port: 3306

