{
 "title": "MYAPP DASHBOARD",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "500 (APP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(myapp_myapp_request_count{status=~\"5.+\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "500 (NGINX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[2m]))"
    }
   ]
  },
  {
   "title": "RPS (APP ENDPOINTS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(myapp_myapp_request_count[2m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "RPS (NGINX ENDPOINTS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(nginx_ingress_controller_request_duration_seconds_count[2m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "RPS (APP STATUS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(myapp_myapp_request_count[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS (NGINX STATUS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "LATENCY (APP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(myapp_myapp_request_latency_bucket[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(myapp_myapp_request_latency_bucket[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(myapp_myapp_request_latency_bucket[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "LATENCY (NGINX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))",
     "legendFormat": "0.99"
    }
   ]
  }
 ]
}