openapi: 3.0.1
info:
  title: Оформление заказа
  version: 1.0.0
tags:
  - name: user
    description: cервис пользователей
  - name: order
    description: сервис заказов
paths:
  /users/register:
    post:
      tags:
        - user
      summary: Регистрация пользователя
      description: Регистрация пользователя.
      operationId: registerUser
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        '201':
          description: Регистрация прошла успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Неправильный запрос
  '/users/{userId}':
    get:
      tags:
        - user
      summary: Ресурс пользователя по id
      description: Вернуть данные пользователя
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: ID пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: Успешный запрос на создание пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Нет доступа к данному пользователю
        '400':
          description: Неправильный запрос
        '404':
          description: Такого пользователя нет
  /orders/create:
    post:
      tags:
        - order
      summary: Создание заказа
      description: Создание пользовательского заказа
      operationId: createOrder
      requestBody:
        $ref: '#/components/requestBodies/Order'
      responses:
        '200':
          description: Успешный ответ
        '400':
          description: Неправильный запрос
        '404':
          description: Пользователь не найден
  '/orders/{userId}':
    get:
      tags:
        - order
      summary: Ресурс заказ по id
      description: Вернуть данные заказа
      operationId: getOrderById
      parameters:
        - name: userId
          in: path
          description: id пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: Успешный запрос на создание пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '403':
          description: Нет доступа к данному пользователю
        '400':
          description: Неправильный запрос
        '404':
          description: Такого пользователя нет
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        address:
          type: string
      required:
        - username
        - password
        - email
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
        address:
          type: string
        totalSum:
          type: number
        products:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
          examples:
            sample-user:
              summary: Обычный пользователь
              value:
                username: ivan
                firstName: Иван
                lastName: Иванов
                email: ivan@ivan.com
                phone: '+700000000'
                password: 'qwerty'
                address: 'ул. Ленина 157 - 17'
      description: Необходимые данные по пользователю
      required: true
    Order:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Order'
          examples:
            sample-array:
              summary: Обычный заказ
              value:
                address: Адрес
                products:
                  - id: 0
                    name: "Наименование товара"
      description: Необходимые данные по заказу
      required: true
