apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: {{ .Values.service.port }}
            path: /login
          - backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: {{ .Values.service.port }}
            path: /signin
          - backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: {{ .Values.service.port }}
            path: /logout
          - backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: {{ .Values.service.port }}
            path: /register
          - backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: {{ .Values.service.port }}
            path: /auth