apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: cm9vdA==
  password: MTIzNDU2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  host: mysql
  db: otus
